### ISSUE TITLE
Not picking up modules from :app gradle module [Windows]

### ISSUE THREAD

**Issue by ursusursus** [square/hephaestus#13] opened 2020-06-24 22:17 UTC
Hi, I was doing exactly what the library is doing but manually before, so I gave it a try. (So pardon the impl, and base interfaces, those shouldnt matter in this case I think)

I might be doing something wrong, however hephaestus doesnt pickup modules in the same gradle module as the mergecomponent is

This is what were the module includes manually

```
@AppScope
@Component(modules = [
	DataModule::class, 
	NetModule::class, 
	MiscModule::class, 
	DomainModule::class, 
	ViewModelsModule::class, 
	ChatModule::class, 
	PaymentModule::class, 
	ExtrasModule::class,
	AppModuleImpl::class 
])
interface AppComponentImpl : AppComponent, million <X>AppComponents {
```

On compilation compiler complains that some bindings are missing, basically the issue is the AppModuleImpl is not there

This is what the generated java with hepheastus is, as you can see the module really is missing, every other module from other gradle modules gets included okay

```
@dagger.Component(modules = 
{
	sk.o2.mojeo2.base.di.DataModule.class, 
	sk.o2.mojeo2.base.di.NetModule.class, 
	sk.o2.mojeo2.base.di.MiscModule.class, 
	sk.o2.mojeo2.base.di.DomainModule.class, 
	sk.o2.mojeo2.base.di.ViewModelsModule.class, 
	sk.o2.mojeo2.base.di.ChatModule.class, 
	sk.o2.payment.data.di.PaymentModule.class, 
	sk.o2.extra.data.di.ExtrasModule.class
}, dependencies = {})
@sk.o2.mojeo2.base.di.AppScope()
public abstract interface AppComponentImpl extends ...
```

![image](https://user-images.githubusercontent.com/1503402/85633254-2c5fdf00-b679-11ea-96ad-2cc19692717a.png)

```
@AppScope
@MergeComponent(AppScope::class)
interface AppComponentImpl : AppComponent {
```
```
@Module
@ContributesTo(AppScope::class)
object AppModuleImpl {
    ...
}
```

**Comment by vRallev** [comment] 2020-06-24 22:34
Can you double check that the Dagger module is on the compile classpath of the Gradle module that is merging modules? Also double check that build types match (e.g. a module in the `debug` folder wouldn't be included in release builds). Otherwise it's hard for me to say what's wrong. Another option is to double check in the Gradle module that contributes the Dagger module that the generated code is there `your_module/build/hephaestus`.

**Comment by ursusursus** [comment] 2020-06-24 22:38
Everything seems to checkout, if I only comment my previous `@Component(modules=...` back in, it works :/

**Comment by vRallev** [comment] 2020-06-24 22:57
I just assume you don't have a 2nd `AppScope` class for some reason? It's hard for me to say what's wrong. Note that you can manually include modules with `@MergeComponent`. Does this work?

**Comment by ursusursus** [comment] 2020-06-24 22:59
I figured you'd need a crystal ball for this one, but I cannot share the whole project as its proprietary. I'll try to keep bashing at it

**Comment by ursusursus** [comment] 2020-06-24 23:15
Yes If I do `@MergeComponent(AppScope::class, modules = [AppModuleImpl::class])` it works. However fails at runtime on a cast, since now it seems this doesnt get included 

```
@ContributesTo(AppScope::class)
        interface MainActivityComponentGetter : AppComponent {
            val mainActivityComponentFactory: Factory
        }
```

also, in the :app module, something is fishy with the :app module

**Comment by vRallev** [comment] 2020-07-01 20:23
Is there anything else I could help you with? Can the issue be closed?

**Comment by ursusursus** [comment] 2020-07-01 21:13
Here is a repro. I think Im doing everything right.

[MyApplication9.zip](https://github.com/square/hephaestus/files/4860568/MyApplication9.zip)

```
C:\...\MyApplication9\app\build\tmp\kapt3\stubs\debug\sk\foo\myapplication\di\AppComponent.java:13: error: [Dagger/MissingBinding] sk.foo.base.Foo cannot be provided without an @Provides-annotated method.
public abstract interface AppComponent extends sk.foo.base.di.BaseComponent {
                ^
      sk.foo.base.Foo is injected at
          sk.foo.base.di.BaseModule.bar(foo)
      sk.foo.base.Bar is provided at
```

**Comment by ursusursus** [comment] 2020-07-03 00:25
I suspect the issue is with the interface replaced with impl, or something

**Comment by vRallev** [comment] 2020-07-04 00:16
I downloaded your project and it builds fine. Here is a [build scan](https://scans.gradle.com/s/btvpv5lf5peia). Not sure what's going on.

**Comment by ursusursus** [comment] 2020-07-04 00:18
Hmm..maybe os? I'm on windows 10

**Comment by vRallev** [comment] 2020-07-04 00:21
Yeah, Mac here. I can't try on another machine. At this point it's worth to file a Kotlin issue.

**Comment by vRallev** [comment] 2020-07-04 06:04
I reactivated my old Windows machine and I was able to reproduce the issue. Your sample project was very helpful. It turned out that even many of the tests in this project fail on Windows. In the end the fix is simple. It's an issue with the file path separator. This will be fixed in the next version. I'll also try to setup Windows machines that run all tests in CI.

**Comment by ursusursus** [comment] 2020-07-05 16:03
Glad I could help. I was planning on writing exactly this library anyways, you saved me time :D

**Closed** 2020-07-05 18:11 UTC
Labels: bug

**Comment by ursusursus** [comment] 2020-07-26 18:00
Hi, I got around back to this. Now it does compile, but does not let the merge component implement the contributing components?

Is this a bug or by design?

`@AppScope
@MergeComponent(AppScope::class)
interface AppComponent {

    @Component.Factory
    interface Factory {
        fun create(@BindsInstance context: Context): AppComponent
    }
}

@ContributesTo(AppScope::class)
interface BaseComponent {
    val bar: Bar
}
//
val appComponent = DaggerAppComponent.factory().create(this).bar....unavailable


// Generated by Dagger (https://dagger.dev).
package sk.foo.myapplication.di;

import android.content.Context;
import dagger.internal.DoubleCheck;
import dagger.internal.InstanceFactory;
import dagger.internal.Preconditions;
import javax.inject.Provider;
import sk.foo.base.Bar;
import sk.foo.base.Foo;
import sk.foo.base.di.BaseModule_BarFactory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DaggerAppComponent implements AppComponent {
  private Provider<Context> contextProvider;

  private Provider<Foo> fooProvider;

  private DaggerAppComponent(Context contextParam) {

    initialize(contextParam);
  }

  public static AppComponent.Factory factory() {
    return new Factory();
  }

  @SuppressWarnings("unchecked")
  private void initialize(final Context contextParam) {
    this.contextProvider = InstanceFactory.create(contextParam);
    this.fooProvider = DoubleCheck.provider(AppModule_FooFactory.create(contextProvider));
  }

  @Override
  public Bar getBar() {
    return BaseModule_BarFactory.bar(fooProvider.get());}

  private static final class Factory implements AppComponent.Factory {
    @Override
    public AppComponent create(Context context) {
      Preconditions.checkNotNull(context);
      return new DaggerAppComponent(context);
    }
  }
}`

**Comment by vRallev** [comment] 2020-07-26 19:00
Is this still the same sample project? Can you upgrade to the latest version? It's strange, because I'm running all tests in CI on a windows machine, too.

**Comment by ursusursus** [comment] 2020-07-26 19:06
Yes its the latest 1.0.5

Anyways, is it expected to modify AppComponent in place like

`interface AppComponent : BaseComponent`?

or rather, only on the dagger generated

`class DaggerAppComponent : AppComponent, BaseComponent` ?

since at runtime, I do can cast the dagger app component to base component, which is weird

**Comment by vRallev** [comment] 2020-07-26 19:14
It's expected to change the byte code and stubs. You can find the stubs in `your_project/build/tmp/kapt3/stubs/...`. Stubs are Java files and there you should see `interface AppComponent extends BaseComponent`. In case you don't see them, can you  upload your updated sample project to Github?

**Comment by ursusursus** [comment] 2020-07-26 19:20
Hmm, I see it there

![image](https://user-images.githubusercontent.com/1503402/88487482-b1def380-cf85-11ea-86bc-79fedfbb5c56.png)

however the dagger generated complains

![image](https://user-images.githubusercontent.com/1503402/88487499-db981a80-cf85-11ea-8a7e-6c87b06968aa.png)

**Comment by ursusursus** [comment] 2020-07-26 19:23
https://github.com/ursusursus/AnvilRepro

here, with /build contents as well

**Comment by vRallev** [comment] 2020-07-26 19:27
Yes, then everything works as expected. The IDE doesn't know that the types are merged, unfortunately.

**Comment by ursusursus** [comment] 2020-07-26 19:31
Kind of sucks since I had code like

```
class AppComponentInitializer {
    fun initialize(appComponent: AppComponent) {
        appComponent.bar.init()
    }
}
```

now I need cast for that

**Comment by vRallev** [comment] 2020-07-26 19:34
You can still do that. Just add the type like you did before. There is no need to rely on the plugin. In a modularized codebase where the app component is created in the app module but everything else happens in library modules you wouldn't be able to do what you try to do.

**Comment by ursusursus** [comment] 2020-07-26 19:36
Yes I would be, not worth explaining, I just need the AppComponent : BaseComponent for the IDE to pick it up. Can we do something about that?

**Comment by vRallev** [comment] 2020-07-27 01:11
This would require an IDE plugin and that's not on the roadmap. If you use a mechanism like highlighted here, then you won't have issues. We use something similar in our apps.

https://github.com/square/anvil/blob/main/sample/scopes/src/main/java/com/squareup/scopes/ComponentHolder.kt#L6-L8
